### ISSUE TITLE
Please, return reset leela cache option

### ISSUE THREAD

**Issue by KimalIsaev** [fohristiwhirl/nibbler#106]
Please, return reset leela cache option. It was In version 1.16-rc1, but in last version(1.47) I couldn't find it, I don't know in which version it was deprecated, but it was very useful for learning openings.

**Comment by fohristiwhirl** [comment]
It's at Engine --> Soft engine reset now.

**Comment by fohristiwhirl** [comment]
Wait, I guess you want the arrows to disappear as well? Hmm...

**Comment by KimalIsaev** [comment]
Thank for response, and if you could, make it some key bind, please.

**Comment by fohristiwhirl** [comment]
To be clear, what specifically do you want the feature to do?

**Comment by KimalIsaev** [comment]
The same thing that "reset leela cache"(F12) button was doing in version 1.16-rc1. Delete all information about already seen positions, and delete drawn arrows.

**Comment by fohristiwhirl** [comment]
Done.
