### ISSUE TITLE
Alternative Known Move Arrow

### ISSUE THREAD

**Issue by cpiscos** [fohristiwhirl/nibbler#107]
The arrow for the known move and Leela's moves are the same. Any way to choose a different one for better visualization?

**Comment by fohristiwhirl** [comment]
Yes, I'll do this.

Question: when the known move is also Leela's best move, should it display in blue, or the new colour?

**Comment by cpiscos** [comment]
I think it should still display in blue. The numbers help differentiate whether or not it was the best move anyways. 

Thank you

**Comment by fohristiwhirl** [comment]
I oscillated between the two options but went with preferring blue for best moves.
