### ISSUE TITLE
[FeatureRequest] New chess pieces

### ISSUE THREAD

**Issue by CiriousJoker** [fohristiwhirl/nibbler#109]
The current ones look kind of dated. Since I haven't found any chess pieces that I like, I'll probably design my own ones that I'll push to Lichess. Is anyone here interested in new pieces as well? I'm currently busy with exams though.

**Comment by fohristiwhirl** [comment]
I've rarely seen pieces I really like either, I guess my favourite is the Chess24 ones.

**Comment by CiriousJoker** [comment]
Interesting, I don't like those as well. I found the chess.com ones looking ok but I'm probably biased because I got used to them. I'm looking for something slightly futuristic, with visual depth, that's still easy to recognize..

**Comment by elyasmehtabuddin** [comment]
![image](https://user-images.githubusercontent.com/44978436/87889516-e59aa600-c9e6-11ea-8f3a-f9b9be472be6.png)
![image](https://user-images.githubusercontent.com/44978436/87889535-f77c4900-c9e6-11ea-8940-95dceb300285.png)
![image](https://user-images.githubusercontent.com/44978436/87889552-06fb9200-c9e7-11ea-8451-7a32ec7a3c43.png)

**Comment by CiriousJoker** [comment]
Cool! Hot reload would be nice to have but isn't important at all. Since ppl can technically view all the pieces quickly by cloning the git repo

**Comment by elyasmehtabuddin** [comment]
I also want to get custom board backgrounds

**Comment by elyasmehtabuddin** [comment]
teaser

![image](https://user-images.githubusercontent.com/44978436/88014544-07be2200-cad4-11ea-84c2-7a9431a95224.png)

**Comment by elyasmehtabuddin** [comment]
update:

![2020-07-22_01-00-49](https://user-images.githubusercontent.com/44978436/88151073-129db300-cbb7-11ea-8df5-3b3016907269.gif)

**Comment by CyanusBird** [comment]
> 
> 
> update:
> 
> ![2020-07-22_01-00-49](https://user-images.githubusercontent.com/44978436/88151073-129db300-cbb7-11ea-8df5-3b3016907269.gif)

how can I have those themes?

**Comment by fohristiwhirl** [comment]
If you can get the pieces as a folder of PNG or SVG files you can select it with the menu item Display --> Pieces

**Comment by CyanusBird** [comment]
> 
> 
> If you can get the pieces as a folder of PNG or SVG files you can select it with the menu item Display --> Pieces

Thanks for your fast reply 🤍, Do you know how to get the pieces? I tried to search on google but I failed...

**Comment by elyasmehtabuddin** [comment]
https://github.com/elyasmehtabuddin/nibbler/tree/elyasm/theme/THEMES
I got themes here you can download, will require some renaming of file and folders though, good luck

**Comment by CyanusBird** [comment]
> 
> 
> https://github.com/elyasmehtabuddin/nibbler/tree/elyasm/theme/THEMES
> I got themes here you can download, will require some renaming of file and folders though, good luck

Thank you very very much, it worked !!, I really admire your work... thanks again for your help
