### ISSUE TITLE
Stockfish dev nnue support

### ISSUE THREAD

**Issue by Zenchess** [fohristiwhirl/nibbler#114]
I don't know if this works, but I've tried loading stockfish dev and choosing a nnue weights file .  Not sure if nnue is even running as I'm not sure how to set engine parameters - but I did notice that it only shows one arrow (the top move) and does not show the line if I hover over a variation.  It does show variations on the right however.

**Comment by fohristiwhirl** [comment]
This is really a Leela-specific GUI. A/B engines aren't really suitable for Nibbler's display since we rely on MultiPV, which drastically reduces their strength.
