### ISSUE TITLE
Feature Request to support running LC0 on an Jetson Xavier server

### ISSUE THREAD

**Issue by JamesCoons** [fohristiwhirl/nibbler#115]
I have my LC0 running on a Jetson Xavier AGX server and the engine I launch on my windows machine just acts to send the UCI commands to an agent on the server. Because of this Nibbler currently will not work on my windows machine since it tells the server to load a network based on a path on my windows machine.

see https://en.chessbase.com/post/running-leela-fat-fritz-on-your-notebook-2 for info about running leela chess on a server

I would like the ability to set a setting that would disable the need to load the network, as that is automatically done on the server side.

**Comment by fohristiwhirl** [comment]
If you find your `config.json` file (via Dev menu) you should be able to edit it and delete the line in the Options that specifies the WeightsFile.

**Comment by JamesCoons** [comment]
That helped a lot. Nibbler now works for the first position I try, but if I make a move it won’t work for that position and gives an error on the server about not being able to overwrite a file. I have to restart Nibbler in order to evaluate a second position. Other applications don’t have that issue.

**Comment by fohristiwhirl** [comment]
Hmm - what error?
