### ISSUE TITLE
Unsure

### ISSUE THREAD

**Issue by DarkChord** [fohristiwhirl/nibbler#116]
3k4/ppp5/8/8/8/8/5PPP/4K3 w - - 0 1

The above is an endgame that yields a forced win for white (starting with Kd2 or h4). When any of my engines run on Arena, they easily find the win in 20 or so seconds, even without a tablebase. When running on Nibbler, an engine (stockfish nor lc0) has never found the win, even with a 6 piece tablebase. I have no idea what may cause this, but I wanted to bring it up because I think it's odd that this is happening, considering Arena found it rather swiftly.

**Comment by fohristiwhirl** [comment]
Hmm. For Stockfish, are you using the same number of threads in both cases? With the right settings I find a win in a few seconds also...

![image](https://user-images.githubusercontent.com/16438795/98045120-dfa6c480-1e1f-11eb-9340-fc2ba4c723be.png)

**Comment by DarkChord** [comment]
I did, yes. It was able to find it in 19 seconds in Arena

**Comment by fohristiwhirl** [comment]
What network for Leela?

**Comment by DarkChord** [comment]
J-320 at the time, I believe
