### ISSUE TITLE
Feature go/halt on screen not in menu.

### ISSUE THREAD

**Issue by ChameleonRed** [fohristiwhirl/nibbler#117]
You added go on screen but there is not halt on screen - it will be nice to do it with mouse as on go.

Go button is here.
![obraz](https://user-images.githubusercontent.com/1080880/98597086-baf79480-22d8-11eb-971b-c8a7548a014f.png)

Can you add similar to halt?
It can be added on first line/number of nodes - click will halt.
![obraz](https://user-images.githubusercontent.com/1080880/98597166-d95d9000-22d8-11eb-94cf-b226ed6874b7.png)

**Comment by ChameleonRed** [comment]
What do you think?

**Comment by fohristiwhirl** [comment]
I forget why it's like this; probably because there are a lot of different "running" states the program can be in (normal, playing 1 colour, reviewing a game, self-play, etc), but only one way for it to be halted. It's possible to add a "halt" button but it might be a bit ugly.

**Comment by ChameleonRed** [comment]
You can hide button under calculations "Nodes ... Time:14s" - click on it will stop.

No need to add explicit button to allow use only mouse.

**Comment by ChameleonRed** [comment]
It can be yellow to keep look and feel.
