### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by GuyBielderman** [fohristiwhirl/nibbler#122]
I love working with Nibbler it does an excellent job for my Lc0.

But i would love to see that a DGT connection and input would be available with the ability to send evaluation to the DGT clock.

Like Arena used to have but that doesn't work anymore because arena doesn't work with the latest drivers.

Keep up the good work

**Comment by fohristiwhirl** [comment]
Probably beyond my powers.

**Comment by GuyBielderman** [comment]
[72002 e-Board protocol description_P1.0.pdf](https://github.com/fohristiwhirl/nibbler/files/5926634/72002.e-Board.protocol.description_P1.0.pdf)

I asked if DGT it self could help us. 

This is the mail i got back

I'm afraid I can't help with the Rabbit Plugin.

For now, I can send you the protocol documentation to communicate with the board and the clock.

I suggest to wait a bit, we are currently planning a new solution, but this wil still take a while. If you can't wait, use the attached file for your needs.

Hope this helps,

If you have further questions, don't hesitate to contact us again.

Regards,

Ulf Bierkaemper | DGT
Product Development

**Comment by fohristiwhirl** [comment]
This is really outside of the scope of what Nibbler is for.
