### ISSUE TITLE
Slow with stockfish 12?

### ISSUE THREAD

**Issue by Wickdhub** [fohristiwhirl/nibbler#123]
Hello!

I just would like to know why, when i use stockfish 12 on nibbler, it takes much more time to nibbler to achieve the same depth as arenadb or scid for example, even with the focus mode. However on the console, i can see that nodes and nodes per seconds are the same on theses 3.

Also is there a possibility to show depth when i use stockfish, or will there be in few updates?

I know nibbler is optimize for Lc0 but I prefer stockfish 12 and I like your display so much! Great job!

**Comment by fohristiwhirl** [comment]
It really isn't recommended to use Nibbler for Stockfish.

If you must, you may need to set the number of threads to use in the Engine menu. But there are other Stockfish settings that Nibbler doesn't know about at all; changing these is still possible via editing Nibbler's own config file, if you really want...

(Do you want to hear more about that?)

**Comment by Wickdhub** [comment]
Thanks for the answer!
Yes why not! I'll try do understand what I can x)

**Comment by fohristiwhirl** [comment]
You can have Nibbler send any UCI option with a little bit of effort. In the Dev menu, click "Show config.json". This will locate Nibbler's own config file. (Close Nibbler while you edit it.)

There's an "options" section which contains whatever UCI commands you want to send.

I'd suggest something like

```
"Threads": 5,
"Hash": 8192,
"Contempt": 0,
"MultiPV": 1
```

I leave it to you to choose the right Thread count and Hash sizes.

**Comment by Wickdhub** [comment]
Thanks! I juste have a problem with the Hash, it says:
 Expected coma json(514) Peek Problem (Alt+F8) No quick fixes available
Will it still runs or do I have to do something else?

**Comment by fohristiwhirl** [comment]
The whole file has to be valid JSON. The most likely problem is commas, each item needs a comma except the last item in the object. Notice how I did it above.

Nibbler does not show depth, it's not really the right metric for Leela.

**Comment by Wickdhub** [comment]
I have copy paste your stuff but the only problem was with the Hash, seems like the variable is not known or things like that :/

**Comment by fohristiwhirl** [comment]
What's happening exactly?

**Comment by Wickdhub** [comment]
It's my bad sorry,it works now I must have made a mistake, thanks for all your advices! Could you just explain me what's the goal of:
"Contempt": 0,
  "MultiPV": 1
looks like I have way less lines in the analysis mod when I had them

**Comment by fohristiwhirl** [comment]
A/B engines like Stockfish don't analyse the whole tree but only moves which might actually affect the final result (this is called A/B pruning). However, in order to produce the Multi-PV display that Nibbler uses, they need to essentially discard that feature.

So setting MultiPV to 1 makes Stockfish use its normal algorithm which is vastly stronger, at the cost of no longer showing all the other moves.

Setting Contempt to 0... uh actually probably has no effect after NNUE.

**Comment by Wickdhub** [comment]
Thanks for all your answers!
