### ISSUE TITLE
Awaiting uciok from engine

### ISSUE THREAD

**Issue by novacekk** [fohristiwhirl/nibbler#129]
I’m not sure if this is a noob question but nibbler had been working fine with Leela until lately. At first it would sometimes show “awaiting uciok from engine” on startup but now it happens more and more often, to the point where it’s almost every time. Not really sure how I can fix it to just show “halted(go)” again. Cheers.

**Comment by sheerun** [comment]
why you closed it?

**Comment by Jazzy-dev** [comment]
What's the solution to this. My nibbler is also annoying me with the Awaiting UCIok. It used to work fine before

**Comment by rooklift** [comment]
If it's Leela using one of the bigger networks it can take a while to load before it sends anything.
