### ISSUE TITLE
Add depth display (probably per-move)

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#137]
For SF etc.

**Comment by Torom** [comment]
First of all, I wanted to thank you for your work to make nibbler work well with A/B engines. I've been using nibbler with Stockfish for a while now, but the new versions are even more comfortable to work with.

Nevertheless, I wanted to ask if you could make it possible for nibbler to display the mate score correctly. At the moment nibbler only shows +/- 128.00 when a mate was found. An output like +/- M[number of moves to mate] would be great.

Thanks for your great work, nibbler is my favorite chess GUI for a while now.

**Comment by fohristiwhirl** [comment]
Sure, why not.
