### ISSUE TITLE
Next move special colour

### ISSUE THREAD

**Issue by CyanusBird** [fohristiwhirl/nibbler#139]
after recent updates, nibbler begins to show next move with no special colour as previous versions. it shows it as a normal move with respective colours.
i tried retrieve my config file but there is no "next_move_colour" and also even if I added it doesn't appear

**Comment by fohristiwhirl** [comment]
Yeah it was sort of an aesthetic choice, but I replaced it with the "outline" option (Display menu).

**Comment by CyanusBird** [comment]
it was so helpful for me but you know what you're doing. keep going with your tremendous work 💙

**Comment by fohristiwhirl** [comment]
Well, any new comments about the outline feature? You dislike it?

**Comment by CyanusBird** [comment]
although it is indeed a good thing, but it kind of eye exhausting comparing to the usual special colour. my laptop has a not so bright screen so I had to keep in mind and tracking also the move in my head.
so I guess for me, I prefer the old option of seeing exactly the next move played it was the top recommended option as it's colour will be best colour move, or it's not and it's alternatives are there. and by the way I always test nibbler as soon as GitHub notifies me and for along time ago, I'm already a big fan sort of 😂💙

**Comment by fohristiwhirl** [comment]
Alright I might add the colour back as an option, possibly a hidden option. Maybe in 1.8.0.

**Comment by CyanusBird** [comment]
thanks very much for your kindness and your great work 💙

**Comment by fohristiwhirl** [comment]
Done in 1.8.0. The new var is `actual_move_colour` if you want to change it in the config.

**Comment by CyanusBird** [comment]
you're a great person. thanks 💙 gonna try it now
