### ISSUE TITLE
macOS: config.json not found in nibbler directory

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#15]
With version 0.5.1, config.json is not found in the nibbler directory any more. This worked well until nibbler version 0.5.0rc1 on my Mac.

There pops up this error message:
`Couldn't find config file. Looked at: /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Helper.app/Contents/MacOS/config.json`

And in the terminal:
```
Main process couldn't find config file. Looked at:
   /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/config.json
```
Had to copy my config.json file into both directories to avoid the error and to run nibbler. Maybe it is related to how main.js gets invoked? My shell script looks like this:
```
#!/bin/bash
export PATH="/usr/local/bin:$PATH"
cd /Users/max/chess/Lc0/nibbler-0.5.1
electron .
```

**Comment by fohristiwhirl** [comment]
Thanks. There's some information I don't have about how things work on the Mac...

Can you open Nibbler, open the Developer Tools, go to the console tab, and type in:

`process.argv[0]`

And let me know what that says?

**Comment by fohristiwhirl** [comment]
Actually, I just pushed a commit that *might* fix it, can you check (after deleting those config files you put in your Electron distribution)... Thanks.

**Comment by twoplan** [comment]
Great, it works now again! Thanks
