### ISSUE TITLE
macOS: paste of fen or epd string

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#23]
First, let me thank you for implementing new features (**"node limit" - like it a lot!**) so quick. 

I'm struggling to paste epd strings like _6k1/p3q2p/1nr3pB/8/3Q1P2/6P1/PP5P/3R2K1 b - - bm Rd6;_ into the line under the chess board. After clearing the field and pasting the position with CMD-V nothing appears there.

Or is this feature not ready yet?

**Comment by fohristiwhirl** [comment]
To clarify, when you say "nothing appears there" you mean you press Paste and the FEN box remains empty?

At the moment it will only accept FEN, but you should at least see what you pasted.

**Comment by fohristiwhirl** [comment]
Anyway, assuming the problem is with pasting itself, try it now. It still won't work for your actual test string, but you could try:

`6k1/p3q2p/1nr3pB/8/3Q1P2/6P1/PP5P/3R2K1 b - - 0 1`

**Comment by twoplan** [comment]
Yes, pressing Paste and the FEN box remains empty. The same happens with CMD-C (copy) from this line. The clipboard remains empty.

**Comment by fohristiwhirl** [comment]
I pushed a commit that might have fixed this 2 hours ago, have you tried since then?

**Comment by twoplan** [comment]
Great, it works now!

**Comment by fohristiwhirl** [comment]
Thanks. These issues supporting 3 platforms... :/
