### ISSUE TITLE
Nibbler GUI only for LCZero?

### ISSUE THREAD

**Issue by yellow-panther** [fohristiwhirl/nibbler#25]
Hello fohristiwhirl,

can you enhance Nibbler in a way that other UCI-compatible- chess engines http://download.shredderchess.com/div/uci.zip  can be embedded into this graphical user interface, too?

Regards,

**Comment by fohristiwhirl** [comment]
It's mostly for Lc0. Another UCI engine should at least run, but various things about the display will be off. In addition, to get more info from the engine, we send a command to the engine which (as a side-effect) weakens non-NN engines.
