### ISSUE TITLE
macOS: minimize window closes Nibbler

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#29]
When you try to minimize (with the yellow button on top left) the Nibbler window into the macOS dock, the program gets closed instead. 

You used the standard shortcut for "minimize to dock" (CMD-M) for "Make this the main line".

**Comment by fohristiwhirl** [comment]
OK, try it now.

**Comment by twoplan** [comment]
Button works now! CMD-M still linked to "Make this the main line".

**Comment by fohristiwhirl** [comment]
Is that going to annoy people?

**Comment by twoplan** [comment]
Take a look here https://support.apple.com/en-us/HT201236

**Comment by fohristiwhirl** [comment]
By the way, I've just done a big refactor of the config loading code, would appreciate if you could check the new version (as of like 2 mins ago) and see if it still works on Mac.

**Comment by twoplan** [comment]
Looks well, I noticed no difference.

**Comment by fohristiwhirl** [comment]
Thanks. Also thanks for your promotion of Nibbler on talkchess, I've already had some interesting contacts as a result.

Do you know the Leela Discord? You might be interested in the chat there.

**Comment by twoplan** [comment]
Hoped the promotion was in your sense. Will take a look at Leela Discord.

BTW, is there  any confirmation on other operating systems after switching the weight file? On mac I notice just different nps from a "faster" network. So switching networks works.

**Comment by fohristiwhirl** [comment]
No there's no confirmation at present.

**Comment by fohristiwhirl** [comment]
Discord is at: https://discordapp.com/invite/pKujYxD
