### ISSUE TITLE
Nibbler 0.66 GUI for Windows with LC0 v0.21.2 Blas

### ISSUE THREAD

**Issue by yellow-panther** [fohristiwhirl/nibbler#37]
Hello fohristiwhirl,
after downloading https://github.com/LeelaChessZero/lc0/releases/download/v0.21.2/lc0-v0.21.2-windows-blas.zip I extracted all files in the same directory where Nibbler066.exe (application) is located. Then a message is visible to rename necessarily config.example.json into config.json. After doing this and invoke Nibbler.exe > error, that no config.json file can be found. Is a pre-configurated weights file on your website available at all and why does your application "Nibbler" does not contain the the current LC0 packages including a redirection link to https://lczero.org/networks/ ? In my opinion the original weightsfile is too long, is is possible to replace this whole alphanumeric order by an abreviation e.g. blas.xyz too?
The contribution http://blog.lczero.org/2018/09/guide-setting-up-leela-on-chess-gui.html  seems to be interesting -  my first GUI for running LC0 was ChessBase graphical interface (Fritz GUI).

Regards,

**Comment by fohristiwhirl** [comment]
> I extracted all files in the same directory where Nibbler066.exe (application) is located

Well this is not really recommended but OK.

> Then a message is visible to rename necessarily config.example.json into config.json.

This is optional but it will certainly find it if it's named exactly `config.json`

> Is a pre-configurated weights file on your website available at all

I don't really have a website. You can get a network from [https://lczero.org/networks/](here) (recommended if you have a powerful GPU, or if you don't, try the [LD2 network](https://lc0.org/ld2) instead.

> why does your application "Nibbler" does not contain the the current LC0 packages

For one thing, they are too large.

> In my opinion the original weightsfile is too long, is is possible to replace this whole alphanumeric order by an abreviation e.g. blas.xyz too

You can change the filename, if that's what you mean.
