### ISSUE TITLE
Feature request: network name in the About-window

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#38]
Sometimes I have difficulties to remember which network gets used for analysis.

Could you add the **name of the loaded weights file** to the About-window?

**Comment by fohristiwhirl** [comment]
This is quite a lot harder than you'd think...

**Comment by fohristiwhirl** [comment]
OK maybe it's not so hard. Done.

**Comment by twoplan** [comment]
Great!

Tiny issue: shows the weight file name when loaded with **config.json**, or after switching the net via menu entry "**Analysis/Switch weight files...**". But not when the weight file was defined in **lc0.config**. Then you display "Weights: undefined".

**Comment by fohristiwhirl** [comment]
That can't really be helped, Nibbler has no knowledge of the lc0.config file at all.
