### ISSUE TITLE
Nibbler crashing when Leela runs out of RAM

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#42]
Report from Windows:

Nibbler has been known to crash when Leela runs out of memory and starts paging. This happened on a system with 64 GB of RAM, some time before 675 million nodes.

Of course Leela running out of RAM is not Nibbler's fault, but why are we crashing?

**Comment by fohristiwhirl** [comment]
Well, I get the impression the Node GC is lazy and not firing until our heap is rather large, which might cause issues if the whole system starts paging. Who knows. Added a "forced" (or rather, requested) GC on a 5 minute loop.

**Comment by fohristiwhirl** [comment]
Received a report of this happening in 0.77.

**Comment by kubiknubika** [comment]
http://lczero.org/play/troubleshoot/ it's lc0's problem. Nibbler only can auto-set max RAM allocated to lc0
