### ISSUE TITLE
Make a Mac OS build

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#43]
This is a thing I should do. @twoplan, if I made a build would you be willing to test it?

**Comment by fohristiwhirl** [comment]
If yes, see https://github.com/fohristiwhirl/nibbler/releases/tag/v0.7.0-mac-experimental

**Comment by fohristiwhirl** [comment]
Postponed for now.

**Comment by twoplan** [comment]
Most people (not only on the mac) want batteries included apps.

Atm, this is a big issue for macOS users

1. you have to compile Lc0 (there is no mac binary)
	- install Apple command line tools
	- install homebrew
	- install with brew python3, meson and ninja
	- install SDK headers (on macOS 14)
	- download and unpack Lc0 source
	- run build script
	- download weights file
2. you have to prepare for Nibbler
	- install node.js
	- install with npm electron
	- download and unpack Nibbler source
	- create config.json

Imo a Nibbler.app, which includes electron Framework, but not Lc0 doesn't make sense for a mac user. Most people struggle with step 1.

Atm it seems enough to **add some tips for experienced mac users**. On talkchess I gave some hints. Feel free to include and modify it for your Readme.md

http://www.talkchess.com/forum3/viewtopic.php?f=2&t=71055&start=10#p802420
