### ISSUE TITLE
Nibbler 0.70 Mac crashes immediately 

### ISSUE THREAD

**Issue by maxchess** [fohristiwhirl/nibbler#44]
Oops - please ignore - big booboo.

**Comment by fohristiwhirl** [comment]
Wait, what was the big booboo? I got someone else saying it crashes, have you got it working?

**Comment by maxchess** [comment]
No not working unfortunately because in my haste I neglected to change the json config file then realised I have yet to compile Lc0 for my Mac. I have quite a few games to play at ICCF and didnt want to get bogged down with Lc0 compile errors. (I have a very weird Mac system in as much as sometimes clang/gcc compiles work and sometimes they dont.)

I was in too much of a rush - my sincere apologies.

**Comment by maxchess** [comment]
I can post the message from the OS if you wish - my booboo may NOT be the issue - I have no idea.
Want me to post the OS message ?

**Comment by fohristiwhirl** [comment]
Sure go on.

**Comment by fohristiwhirl** [comment]
Gonna postpone the Mac build for now.

**Comment by fohristiwhirl** [comment]
I know what the reason is btw - the directory structure has a bunch of symlinks which aren't getting packaged properly on my non-Mac machine.
