### ISSUE TITLE
macOS Nibbler

### ISSUE THREAD

**Issue by maxchess** [fohristiwhirl/nibbler#45]
Hellooo !
Just wondering if the macOS dev is on hiatus (indefinitely) ?
The Windows version works just fine.

**Comment by fohristiwhirl** [comment]
I think yes, however if you wanted to make an unofficial Mac build I think it would be possible.

Basically the process is:

* Download and unpack the Darwin version of Electron, e.g. https://github.com/electron/electron/releases/download/v5.0.6/electron-v5.0.6-darwin-x64.zip
* Dump the Nibbler files into `Electron.app/Contents/Resources/app/`
* Move `config.example.json` to the top level

**Comment by twoplan** [comment]
@fohristiwhirl
Faultily commented at a **closed topic** on your github repo, so you missed it. The link to my view about a macOS Nibbler.app https://github.com/fohristiwhirl/nibbler/issues/43

Anyway I followed your description above and could start the app. But ..
![error-1](https://user-images.githubusercontent.com/7384966/60721325-d5c03900-9f2d-11e9-9f62-f44dd733abaa.png)

**Comment by fohristiwhirl** [comment]
Ah right yeah.

Try renaming Electron.app to Nibbler.app.

**Comment by twoplan** [comment]
![error-2](https://user-images.githubusercontent.com/7384966/60721697-0eacdd80-9f2f-11e9-9b30-6d53467a552b.png)

**Comment by twoplan** [comment]
How about a load config file option in Nibbler?

**Comment by fohristiwhirl** [comment]
Does everything else work, i.e. pieces load, you can make moves, etc (but no Leela of course) ?

**Comment by twoplan** [comment]
Yepp, as fas as I tested.

**Comment by fohristiwhirl** [comment]
I guess it's this: https://www.synack.com/blog/untranslocating-apps/

**Comment by fohristiwhirl** [comment]
Does putting the config.json file into the same folder as the rest of the source fix it?

**Comment by twoplan** [comment]
.. reads horrible! Please note, that I run macOS 10.13.6 here.

**Comment by twoplan** [comment]
**Yes, putting it to the source fixes it!**

**Comment by fohristiwhirl** [comment]
I mean it's not really a solution.

A properly working Mac build will probably have to wait till I do real preferences, so we can do away with config.json.

**Comment by maxchess** [comment]
Hey wait - dont rush me - I'm an old man.
So it works - congrats.
Any chance of a Mac binary .. please !!!!

**Comment by maxchess** [comment]
Mojave 10.14.5
Running via an external HD because my Fusion drive is kaput.
Waiting for the machine to give up the ghost.

**Comment by twoplan** [comment]
This seems to be a permission issue. 

When I create a folder /opt/Nibbler with sudo and put there lc0 & weights all works nice. 

config.json goes to Nibbler.app/Contents/Resources/app and looks like
```
	"path": "/opt/Nibbler/lc0",
	"options": {
		"Backend": "blas",
		"WeightsFile": "/opt/Nibbler/bad-gyal-2.pb.gz"
```
Pretty ugly, but it works.

**Comment by fohristiwhirl** [comment]
It's essentially postponed for a while.
