### ISSUE TITLE
Nibbler 0.77 GUI win64 problem including 0.21.2 Lc0

### ISSUE THREAD

**Issue by yellow-panther** [fohristiwhirl/nibbler#49]
Hello fohristiwhirl,

I downloaded and extracted https://github.com/LeelaChessZero/lc0/releases/download/v0.21.2/lc0-v0.21.2-windows-blas.zip + https://lc0.org/ld2 and renamed just the last file into weights6-swa-20000 (because my pc does  not possess a GPU)

That works with the external graphical interfaces Arena www.playwitharena.de and WinBoard AA beta http://hgm.nubati.net/WinBoard-AA.zip of course, but after launching Nibbler 0.77 exists an error message: "couldn´t spawn process - check the paths in the comfig file and use absolute paths."

The config.example.json is unchanged.
What is the suggestion in this case to run Lc0 21.2 with Nibbler GUI 0.77, please?

Regards,

**Comment by yellow-panther** [comment]
By the way: all Lc0+GUI files are situated into the directory  C:\User\Downloads\nibbler-0.7.7-windows

**Comment by maxchess** [comment]
Hello @yellow-panther :

have you changed the config file ?
If not you're supposed to alter the settings to point to the paths where Lc0 and your weights file are located - after that rename the config.example.json to config.json

In your case you should point those files to your folder here C:\User\Downloads\nibbler-0.7.7-windows - a suggestion - perhaps move to your desktop.

I hope I did not misunderstand !

**Comment by fohristiwhirl** [comment]
Renaming the config file is optional, but (given what you've said) its contents should include something like:

`"path": "C:\\User\\Downloads\\nibbler-0.7.7-windows\\lc0.exe"`

And the WeightsFile should likewise be specified.

**Comment by yellow-panther** [comment]
{
	""path": "C:\\User\\Downloads\\nibbler-0.7.7-windows\\lc0.exe"

",

	"options": {
		"Backend": "cudnn",
		"WeightsFile": "C:\\User\\Downloads\\nibbler-0.7.7-windows\\lc0.exe"
	},

	"args": [],

	"NOTE": "Users with high resolution monitors may want to increase the sizes below.",

	"width": 1280,
	"height": 835,
	"board_size": 640,
	"info_font_size": 16,
	"pgn_font_size": 16,
	"fen_font_size": 16,
	"status_font_size": 16,
	"arrow_width": 8,
	"arrowhead_radius": 12,
	"board_font": "18px Arial",

	"light_square": "#dadada",
	"dark_square": "#b4b4b4",
	"active_square": "#66aaaa",
	"move_colour": "#ffff00",
	"move_colour_alpha": 0.15,
	"best_colour": "#66aaaa",
	"good_colour": "#66aa66",
	"bad_colour": "#cccc66",
	"terrible_colour": "#cc6666",
	"bad_move_threshold": 0.02,
	"terrible_move_threshold": 0.04,
	"uncertainty_cutoff": 0.1,
	"arrowhead_type": 0,
	"show_cp": false,
	"cp_white_pov": false,
	"show_n": false,
	"show_n_abs": true,
	"show_p": true,
	"show_v": false,
	"show_q": false,
	"show_d": false,
	"show_u": false,
	"show_q_plus_u": false,
	"searchmoves_buttons": true,
	"hover_draw": false,
	"hover_method": 0,
	"serious_analysis_mode": false,
	"sam_ev": true,
	"sam_n": true,
	"sam_n_abs": false,
	"sam_of_n": true,
	"sam_p": false,
	"sam_v": false,
	"sam_q": false,
	"sam_d": false,
	"sam_u": false,
	"sam_q_plus_u": false,
	"update_delay": 170,
	"animate_delay_multiplier": 4,
	"search_nodes": "infinite",
	"save_enabled": false,
	"override_piece_directory": null,
	"logfile": null,
	"log_info_lines": false
}
I used NotePad++ https://notepad-plus-plus.org/, but after starting nibbler.exe 
"failed to parse "path": "C:\\User\\Downloads\\nibbler-0.7.7-windows\\config.json" - make sure it is a valid JSON, and if Windows, use \\ instead of\ as a path separator

**Could you please upload a working win64-NibblerGUI with the mentioned above components (Lc0 21.2 for Windows Blas, weights file ld2) on a website like Google Drive please?**
15 GB disk space are free on  https://www.google.com/intl/en-GB_ALL/drive/
By the way: Other GUIs are easier to handle - do you plan to enhance Nibbler graphical  interface e.g. for matches between UCI-compatible engines? cf. survey http://www.computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list (ComputerChess Wiki)

**Comment by fohristiwhirl** [comment]
Most things have their defaults, and if the network (which you're supposed to specify as WeightsFile, as I said) is present in the same folder, Lc0 may well discover it automatically, so you might manage with just this as your config file:

```
{
    "path": "C:\\User\\Downloads\\nibbler-0.7.7-windows\\lc0.exe"
}
```

**Comment by fohristiwhirl** [comment]
By the way, I'm in the process of changing things so the config file isn't necessary at all. Expect a new release within 24 hours.

@twoplan - perhaps you're interested in this? The current version of the repo should be capable of running with no config file.

**Comment by yellow-panther** [comment]
Just a double-mouse-click on nibbler.exe without any configuration file would be great!!

**Comment by fohristiwhirl** [comment]
Yeah, working on it.
