### ISSUE TITLE
0.7.8: without config file

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#50]
Should Nibbler find lc0 and the weights by itself? At my mac this part didn't work. 

After selecting the engine with `Find engine...` Lc0 starts with this error message
![error](https://user-images.githubusercontent.com/7384966/61366208-6a5d5c00-a889-11e9-9dea-d81af6771efb.png)
and **loads the tablebases, but _not the weights_**! Which seems strange, as both path names are in my lc0.config. And `--backend=blas` is there too.

Loading weights manually worked. 

Save `config.json...` should move the focus to the Nibbler directory and name it correct. It points to the last directory, from where the weights was loaded.
![save](https://user-images.githubusercontent.com/7384966/61367055-28351a00-a88b-11e9-886a-a9ac6521396d.png)
After the next start of Nibbler (with the newly written config.json) the --backend error comes again, but all works as expected.

**Comment by fohristiwhirl** [comment]
No it doesn't try to find the app or weights itself. But 0.7.8 at least allows you to find them from inside Nibbler, which is a big improvement.

About the Backend option, was there any sort of Nibbler config or config.example file present that specificied a different Backend?

> Save config.json... should move the focus to the Nibbler directory

Yeah true.

**Comment by twoplan** [comment]
> About the Backend option, was there any sort of Nibbler config or config.example file present that specified a different Backend?

There was only the provided `config.example.json` present

**Comment by fohristiwhirl** [comment]
That overrides your lc0.config, I'm afraid. Hmm.

**Comment by twoplan** [comment]
Without config.example.json version 0.7.9 works great with my lc0.config!

How about changing this message at the beginning to a `Select engine` dialog? 
![engine](https://user-images.githubusercontent.com/7384966/61370923-d47afe80-a893-11e9-88fd-f79baac4580a.png)

**Comment by twoplan** [comment]
Shouldn't Lc0 specific configurations be done in lc0.config instead of config.(example.)json?

**Comment by fohristiwhirl** [comment]
lc0.config is an optional Leela specific thing. Nibbler's config.json can contain anything or nothing in its options section.

**Comment by twoplan** [comment]
Final version 0.7.9 works here without error messages (and with config.example.json in Nibbler directory) when following these steps:

- 1st select backend and choose weights file
- 2nd select engine

**Comment by fohristiwhirl** [comment]
Yeah. The order doesn't really matter except for some error messages that will be produced.

**Comment by fohristiwhirl** [comment]
@twoplan The config.json is now a thing of the past (well it still exists but hidden away...)
