### ISSUE TITLE
Nibbler GUI: separate path to endgame tablebases

### ISSUE THREAD

**Issue by yellow-panther** [fohristiwhirl/nibbler#51]
Hello fohristiwhirl,
other graphical interfaces like Arena www.playwitharena.de , ChessGUI http://www.chess.hylogic.de/  or WinBoard AA Beta http://hgm.nubati.net/WinBoard-AA.zip possess an extra path to egtbs
cf. http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:egtbs_list Especially Gaviota, Nalimov and Syzygy are very common
Would such a feature under "Engine" for Nibbler GUI be an improvement (>upcoming editions)? 
Regards,

**Comment by fohristiwhirl** [comment]
Maybe.

But you can also put [SyzygyPath](https://github.com/LeelaChessZero/lc0/wiki/Lc0-options) in your config file options section.
