### ISSUE TITLE
Version 1.01rc2 on macOS

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#53]
Small feedback about version 1.01rc2 on macOS.

- started Nibbler with electron . from the terminal (without any config.json file)
- selected lc0 engine and weights, changed some sizes and nodes
- closed nibbler and got this message at the terminal:
```
$ electron .
objc[4281]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8daadcd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x113fa7cd8). One of the two will be used. Which one is undefined.
```

After the next start, this message did **not** show up again. Great, Nibbler remembered all previous made changes! 

Looks like ~/Library/Application Support/Nibbler with it's config.json works for you!

**Comment by fohristiwhirl** [comment]
Looks like that message comes when opening a dialog box (e.g. an Open dialog). Don't think I can fix it.

**Comment by twoplan** [comment]
Yeah, the message comes in every session after using the file dialog (choosing weights, engine).

I like the new "Save window size" option in rc3! Pretty sure, select "Piece set" and "Board color" find their way into rc4 ;-)

**Comment by fohristiwhirl** [comment]
I think your thread on TalkChess is the de facto "update announcement" location, I dunno if you'd like to tell them about developments. Specifically, that config.json editing is mostly unneeded now, and engine / weights can be selected via the menu...

Meh, up to you, if you have the inclination.

**Comment by twoplan** [comment]
Done and thanks for your work! 🥇

**Comment by fohristiwhirl** [comment]
Thanks.
