### ISSUE TITLE
Pieces showing only on non-playing side

### ISSUE THREAD

**Issue by BTZK** [fohristiwhirl/nibbler#58]
As the title says.
Screenshot: http://prntscr.com/otiu8d
(I changed pieces set but the problems shows up also with default set.)
Windows 10 Home
Nibbler 1.0.9

**Comment by fohristiwhirl** [comment]
That's peculiar. Can you try:

- Downloading the package again, and / or
- Deleting the entire Nibbler prefs folder, which is at something like:

`C:\Users\<name>\AppData\Roaming\Nibbler`

**Comment by fohristiwhirl** [comment]
Also, if the problem persists, can you open the dev tools (Dev --> Toggle Developer Tools) and click on the console tab at the top, and see if there's anything written there? Thanks.

**Comment by BTZK** [comment]
I did both, I rebooted, and the problem persists.
Console output is empty: http://prntscr.com/otjbzs

**Comment by fohristiwhirl** [comment]
Is this the first version of Nibbler you've used, or have you used previous versions?

**Comment by fohristiwhirl** [comment]
Friendly pieces and hostile pieces (for the player to move) are drawn in fundamentally different ways, one via HTML canvas and one via HTML tables. I don't suppose there's any special software on your machine that might want to interfere with such tables?

**Comment by BTZK** [comment]
This is the first version of Nibbler I use so let's say I've "always" got this problem.
The problem persists even after a fresh boot with close to none softwares open so I don't think there should be any interferences.

**Comment by fohristiwhirl** [comment]
OK thanks. Two questions:

How much effort are you willing to put into helping fix this? (Feel free to say none...)

Do you have any programming experience yourself?

**Comment by BTZK** [comment]
I have programming experience only in python.
I don't really know where to look to fix this.
The only way to make it work for me right now is running Nibbler on my linux boot.

**Comment by fohristiwhirl** [comment]
OK, I'll have a think about what we can try.

**Comment by fohristiwhirl** [comment]
Firstly, I think from your screenshot, you're running your OS at something other than 100% resolution. That really shouldn't matter, and doesn't seem to matter for me, but just to make sure, can you try changing that back, here:

![image](https://user-images.githubusercontent.com/16438795/63209527-e7befb00-c0d9-11e9-8ea4-a980d429f228.png)

**Comment by BTZK** [comment]
It doesn't fix it.
Additional details: when i grab the invisible piece the cursor has a dotted box under it.
http://prntscr.com/otu4a7 (Sorry for the quality i had to take a picture with my phone, couldn't screenshot directly)

**Comment by fohristiwhirl** [comment]
That's normal.

I'll keep thinking...

**Comment by fohristiwhirl** [comment]
Was the alternate piece set you tried earlier using svg or png files?

I wonder if using PNG files might fix it...

**Comment by BTZK** [comment]
I used both SVG (default) pieces and PNG (custom) pieces.
[The set is called Alpha https://marcelk.net/chess/pieces/]

**Comment by fohristiwhirl** [comment]
Alright, I've got it, it's the apostrophe in your path.

I'll have a think about how to fix this.

**Comment by fohristiwhirl** [comment]
Although hmm, when I test it here, there's still a visual flicker that shouldn't exist, if the path contains an apostrophe. Another thing I need to look at.
