### ISSUE TITLE
Issue for posting screenshots

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#6]
![image](https://user-images.githubusercontent.com/16438795/58802783-e9624200-8605-11e9-824c-ca736dde67cc.png)

**Comment by fohristiwhirl** [comment]
![Untitled](https://user-images.githubusercontent.com/16438795/58832441-d4f26980-8646-11e9-8126-0c9b5e53166f.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/58984287-9a1c3d00-87d0-11e9-9616-9b1e410447e7.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/59159439-7c492380-8ac1-11e9-9dde-71c1353c5909.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/59391936-cce4a900-8d6d-11e9-8a53-5ea1ac89c56a.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/59531566-2ff54d80-8ede-11e9-9b7d-7c75be6699f9.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60088521-b4de3380-9736-11e9-9007-25013f48e2af.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60089290-10f58780-9738-11e9-828a-6ebac5366376.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60182999-4fb13d80-981d-11e9-81ee-55193aeb6d9e.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60183311-f85f9d00-981d-11e9-8a53-7e9589680393.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60183484-52606280-981e-11e9-9c10-4bb305023c35.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60507333-d489d480-9cbf-11e9-905f-c0386fc65255.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/60531026-fef48580-9cf1-11e9-964e-723d502cfc72.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/62428006-b0247c00-b6f3-11e9-875b-d8f4ce9a3707.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/62428191-a7817500-b6f6-11e9-991e-3084e163cf4f.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/62624153-59e55200-b91a-11e9-818a-75c9ad0a4a5f.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/80318896-34c8a480-8805-11ea-8e69-0171241b5333.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/80322896-d826b300-881f-11ea-9070-01434e604c4b.png)

**Comment by fohristiwhirl** [comment]
![image](https://user-images.githubusercontent.com/16438795/80602436-088c6e00-8a27-11ea-8163-d26b176f17af.png)

**Comment by rooklift** [comment]
![image](https://user-images.githubusercontent.com/16438795/146676341-54fee65a-d7e3-484d-8234-d2a6594ca2c9.png)

**Comment by rooklift** [comment]
![image](https://user-images.githubusercontent.com/16438795/190862070-47fbcdc7-6709-4001-9e81-95c13efb089a.png)

**Comment by yuzisee** [comment]
Screenshot with #239 #238 #237 #235 all together

![image](https://github.com/rooklift/nibbler/assets/523543/1c12e02a-d322-4ca4-a8ae-34b93b06913a)

**Comment by rooklift** [comment]
![image](https://github.com/rooklift/nibbler/assets/16438795/a432ea17-3601-4143-bddb-97420a0d6e6c)
