### ISSUE TITLE
Can't open Nibbler with double click in Linux

### ISSUE THREAD

**Issue by tran184** [fohristiwhirl/nibbler#63]
I just can open it with ./nibbler.
Please tell me how to open Nibbler with double click.

**Comment by fohristiwhirl** [comment]
Not on Linux myself, so I'm not sure.

**Comment by tran184** [comment]
By the way, How can I change Lc0's threads.

**Comment by fohristiwhirl** [comment]
There's a Threads submenu in the Engine menu, although it is not recommended that you use this if you're running with a GPU.

**Comment by tran184** [comment]
Oh, it's right there, I didn't notice.

**Comment by tran184** [comment]
Nibbler says "OpenBlas using 1 core(s) for this backend". I changed the threads option from 1 to 2 but it seems not to work.

**Comment by fohristiwhirl** [comment]
THat message is from Leela. But threads and BLAS cores aren't the same thing, I'm told.

**Comment by fohristiwhirl** [comment]
The double-click thing is probably a permissions thing, and you need to do `chmod 644 nibbler` or something along those lines.
