### ISSUE TITLE
Nibbler on iPadOS

### ISSUE THREAD

**Issue by all12** [fohristiwhirl/nibbler#64]
Is Nibbler ready to be used on iPadOS?
And iPad Pro 3 and 4?
With the iPadOS it should be even possible to use the magic mouse!, the magic trackpad and also the bluetooth keyboard from an iMac or Mac Pro. Also it's possible to see the display on a big monitor or tv. The handling is also superb. And programming is now much much easier and faster.

Best regards

**Comment by fohristiwhirl** [comment]
I'm afraid not. I wouldn't know where to begin, and anyway not sure Electron can be used for this.
