### ISSUE TITLE
Problem with FEN (to strict parser)

### ISSUE THREAD

**Issue by ChameleonRed** [fohristiwhirl/nibbler#65]
Window 10
Prebuilt 1.1.1
![obraz](https://user-images.githubusercontent.com/1080880/65459316-ece93580-de4f-11e9-96e6-5ebe17b87148.png)

Problem is with FEN from Position Trainer:
r1bqkbnr/pp1ppppp/2n5/2p5/2P1PP2/8/PP1P2PP/RNBQKBNR b KQkq -

![obraz](https://user-images.githubusercontent.com/1080880/65459398-1a35e380-de50-11e9-8f33-98124800c477.png)

Chessdb:
r1bqkbnr/pp1ppppp/2n5/2p5/2P1PP2/8/PP1P2PP/RNBQKBNR/ b KQkq - 0 0
![obraz](https://user-images.githubusercontent.com/1080880/65459474-46e9fb00-de50-11e9-9334-7854da778c95.png)

Problem is because parser is to strict. I programmed parser in Python for FEN which accept all syntaxes.

**Comment by fohristiwhirl** [comment]
These examples are fixed in the repo and thus in the future v1.2.1.
