### ISSUE TITLE
Tiny display glitch with Lc0 0.23.x on macOS

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#69]
Lc0 version 0.23.x shows its logo in red. Nibbler doesn't interpret (or ignore) these esc-sequences for the terminal on macOS and the output gets a little puzzled. 
 
![Lc0-0 23 2+Nibbler](https://user-images.githubusercontent.com/7384966/72082749-ec8e8080-3300-11ea-89af-765d0e367ea0.png)

**Comment by fohristiwhirl** [comment]
Hmm. Dunno what to do about that, probably nothing. :)
