### ISSUE TITLE
White text on white background in Linux for Electron 8

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#70]
There's a report that, under Arch Linux and Electron 8, menu items are white text on white background.

![image](https://user-images.githubusercontent.com/16438795/74591053-5ee33680-500c-11ea-8cbd-6da27d4262db.png)

(Can anyone else confirm / deny?)

**Comment by lealgo** [comment]
It *might* be some issue with the user's theme. But I can't reproduce it here. I've tried every theme I have and the menus always show with the proper colours.

**Comment by fohristiwhirl** [comment]
Thanks.
