### ISSUE TITLE
Nibbler doesn't recognise Syzygy's rtbz, rtbw files as DTZ and WDL files.

### ISSUE THREAD

**Issue by SimonUnderwood** [fohristiwhirl/nibbler#71]
I'm trying to integrate Syzygy endgame tablebase into Nibbler using SyzygyPath. I have already generated all the Syzygy files but when I try to call them using "SyzygyPath": "C:\\Lc0 folder\\Syzygy folder\\"  it says it has found 0 WDL files 0 DTM files and 0 DTZ files. My files are .rtbz and .rtbw files which made me think they're the wrong file type but according to Syzygy's GitHub page .rtbz is DTZ files and .rtbw is WDL files. Now I've hit a dead-end. It would be useful to know exactly what files nibbler is looking for but I don't want to search into nibbler and Lc0's base code.

**Comment by fohristiwhirl** [comment]
Nibbler has no knowledge of tablebases at all, but I believe you can tell Leela can use them.

**Comment by SimonUnderwood** [comment]
I solved my issue now. I put command SyzygyPath on the wrong line. This issue can be closed
