### ISSUE TITLE
Castling in Chess 960

### ISSUE THREAD

**Issue by SimonUnderwood** [fohristiwhirl/nibbler#72]
Nibbler doesn't recognize castling in chess 960 and you can't tweak the FEN to allow it.

**Comment by fohristiwhirl** [comment]
I'm afraid it wasn't built with Chess 960 in mind.

**Comment by SimonUnderwood** [comment]
It would be a pretty easy fix though. 
Just check if the rook and king have moved yet instead of whether they're on the right square.

**Comment by fohristiwhirl** [comment]
This is in progress now.

**Comment by SimonUnderwood** [comment]
Yay thanks
