### ISSUE TITLE
Draw notification

### ISSUE THREAD

**Issue by SquarishRectangle** [fohristiwhirl/nibbler#73]
I'm posting a few questions on this day and I just realised I didn't say what software config. I am using
Win 10 Pro
Nibbler 1.1.3 / Electron 5.0.13
Lc0 v0.23.2

There's no immediate sign that there's a draw. That might not be as bad for a stalemate but for 3 fold repetition especially for the non-obvious ones, and 50 moves no capture no push limit though you can see it from the FEN. 

Similar issues for winning especially because it displays + in PGN instead of #.

**Comment by fohristiwhirl** [comment]
The # mark for checkmate is now in.

**Comment by fohristiwhirl** [comment]
This is now generally displayed if the engine is running.
