### ISSUE TITLE
Moves animation?

### ISSUE THREAD

**Issue by lealgo** [fohristiwhirl/nibbler#76]
Would it be too difficult to add moves animation? It's nice when browsing games.

**Comment by fohristiwhirl** [comment]
It's not what I would call trivial, certainly...

**Comment by lealgo** [comment]
Yeah I figure it may not be super easy. I'd peek at how lichess do it, maybe they found a silly way to do it. If only I knew *some* js... :P

**Comment by CiriousJoker** [comment]
Just judging by design it looks like https://chessboardjs.com/ is used. Doesn't that support animations already?

**Comment by fohristiwhirl** [comment]
> Just judging by design it looks like https://chessboardjs.com/ is used.

It's not.

**Comment by CiriousJoker** [comment]
In that case, is it possible to use that one? It seems to have quite a lot of features in general

**Comment by fohristiwhirl** [comment]
No.

**Comment by CiriousJoker** [comment]
Can you elaborate?

**Comment by fohristiwhirl** [comment]
It would be a huge, disruptive change.
