### ISSUE TITLE
Colors rendered differently

### ISSUE THREAD

**Issue by lealgo** [fohristiwhirl/nibbler#78]
Sorry if this is a very minor nitpick...

![nib](https://user-images.githubusercontent.com/12534727/79669550-56cd8180-818a-11ea-8389-e815959cd7c5.png)

From left to right: scid, xboard, nibbler.

I noticed a different tone to the square colors in nibbler, they seem colder.

**Comment by fohristiwhirl** [comment]
Those are indeed different colours, but what does your config file say?

According to GIMP, on the left you have:

* Dark: d18b47
* Light: ffce9e

Whereas in Nibbler you apparently have:

* Dark: d78a4f
* Light: ffcea2

**Comment by lealgo** [comment]
This is from my nibbler's config:

```
	"light_square": "#ffce9e",
	"dark_square": "#d18b47",
```

So maybe an issue with Electron, Gnome, Ubuntu?

**Comment by fohristiwhirl** [comment]
I've no idea.

**Comment by lealgo** [comment]
It's no big deal. I'll leave the versions I use for reference:

npm@3.5.2
nodejs v8.10.0
Electron 8.2.3
Gnome 3.28.2
Ubuntu 18.04

**Comment by fohristiwhirl** [comment]
While I've got your attention, can you, being a Linux user, confirm you're not having this issue:

https://github.com/fohristiwhirl/nibbler/issues/70

**Comment by lealgo** [comment]
This seems to be the issue:

https://github.com/electron/electron/issues/10732

Passing `-force-color-profile=srgb` on the command line complains but still fixes the issue.

**Comment by lealgo** [comment]
This fixes the issue:

on `main.js`:
```
electron.app.commandLine.appendSwitch('force-color-profile', 'srgb');
```
maybe detect linux and pass the flag?

**Comment by lealgo** [comment]
But right we don't know if it occurs on every Linux...

**Comment by lealgo** [comment]
Upgraded to Ubuntu 20.04 and this issue went away. I'm not sure what fixed it but I'm closing the issue.
