### ISSUE TITLE
openDialog error

### ISSUE THREAD

**Issue by lealgo** [fohristiwhirl/nibbler#81]
I'm getting this error since 1.2.1, it works well in 1.2.0.

![nibbler-file-open](https://user-images.githubusercontent.com/12534727/80152485-bdd3a780-8589-11ea-86ee-635502f6f60c.png)

Operating system: Ubuntu 20.04
Running from source
Version of Nibbler: 1.2.1
Electron: 8.2.3

**Comment by lealgo** [comment]
I think this is the commit:

https://github.com/fohristiwhirl/nibbler/commit/c92d5f5f21d8bcfedc60087dded2819e3972881d

**Comment by fohristiwhirl** [comment]
Thanks, can you try it now?

**Comment by lealgo** [comment]
Yes, it's fixed now. Thank you!
