### ISSUE TITLE
Out of sync issue

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#87]
MadMike1234 writes ([here](https://github.com/LeelaChessZero/lc0/issues/1249)):

> V0.25 with Nibbler v1.2.4
> Nibbler working fine with Stockfish but with any leela doesnt work anymore. I used CUDA version.
>
> It was working 0.25 rc1 with nibbler 1.1.7 but I deleted because I wanted newest version and after that no any combination working.. I tried lot of different leelas nibblers but all the time the same "OUT of SYNC". I have Nvidia 750 .. i7 16GB.. Windows 7 x64
>
> And yes, leela benchmark working well...
>
>Is it possible that either Nibbler or Leela put something in the registry base that could cause this problem?

And also:

> Also, I cant add Leela under Fritz, maybe that is connected.

**Comment by fohristiwhirl** [comment]
Can you submit a screenshot of what you see?

I might have more detailed instructions afterwards.

> Is it possible that either Nibbler or Leela put something in the registry base that could cause this problem?

I don't think either program uses the registry.

**Comment by MadMike1234** [comment]
> Can you submit a screenshot of what you see?
> 
> I might have more detailed instructions afterwards.
> 
> > Is it possible that either Nibbler or Leela put something in the registry base that could cause this problem?
> 
> I don't think either program uses the registry.
> 
> > Also, I cant add Leela under Fritz, maybe that is connected.
> 
> That seems relevant, yes. One thing that occurs to me - you're definitely pointing the GUIs at `lc0.exe` and not `client.exe`?

Yes thats correct on lc0.exe. Is that correct?

Please see provided screenshoots:
![FRITZ UCI](https://user-images.githubusercontent.com/64505251/80609810-d84dcb00-8a38-11ea-9fef-484b13e14b16.png)
![Leela 2 -Nibbler](https://user-images.githubusercontent.com/64505251/80609817-da178e80-8a38-11ea-9139-7cc303e41951.png)
![Leela 1 Nibbler](https://user-images.githubusercontent.com/64505251/80609818-dab02500-8a38-11ea-8fa3-1c4ea6d97719.png)
![Stockfish_22-Nibbler](https://user-images.githubusercontent.com/64505251/80609820-dab02500-8a38-11ea-8975-5a5aed59da79.png)

**Comment by MadMike1234** [comment]
On 2nd scrs. you can see OUT of SYNC. In the meantime I tried other enginees but only new Stockfish 11 working with Nibbler. I tried Komodo 10.1, Stosckfish 6 and they doesnt work.

**Comment by fohristiwhirl** [comment]
Hmm. Nibbler has the ability to log input and output - if you could enable that it would make understanding the issue easier. If you'd like to help, here's some precise instructions...

In the app menu, click "Show config.json". You should be shown a text file.

Quit Nibbler.

Open the text file config.json in a text editor and find the line

`"logfile": null,`

Replace this with

`"logfile": "nibbler.log",`

(Note that the quotation marks and comma must all exist.)

Secondly, replace

`"log_info_lines": false`

with

`"log_info_lines": true`

(Note there is NO comma on this one (being at the end of the list of options).)

Save the file and restart Nibbler. It will now generate a log file. Reproduce the problem, then find the logfile called nibbler.log and upload it here, or on pastebin.com.

**Comment by fohristiwhirl** [comment]
Now that I think about it, from the screenshot it looks like Lc0 never loaded at all. I wonder if it's some sort of permissions issue. It's been a long time since I used Windows 7, but can you try launching lc0.exe directly (i.e. double click its icon) and seeing whether Windows objects?

**Comment by MadMike1234** [comment]
Thanks for quick response. Please find attached log file and Leela after "Go nodes 100" command. also benchamrk with "CMD" working well. 
[nibbler.log](https://github.com/fohristiwhirl/nibbler/files/4552562/nibbler.log)
![Leela Go Nodes 100](https://user-images.githubusercontent.com/64505251/80614042-4648c100-8a3e-11ea-8416-57280963c076.png)

**Comment by MadMike1234** [comment]
And yes I am starting Nibbler as Admin but not Leela. And I dont have to use client.exe at all? Thats what I realized but just to double check?

**Comment by fohristiwhirl** [comment]
Thanks. From the log, it seems that Lc0 is simply not starting. I can't explain why exactly, but the same problem in Fritz suggests it's not really a Nibbler problem, I think.

**Comment by fohristiwhirl** [comment]
Perhaps now you need to set Fritz also to run as admin (if you so trust it).

**Comment by MadMike1234** [comment]
Ahh at last it working good :-D This is offtopic but do you have any suggestion whats the best setup in Nibler with leela? I mean in Analysis menu and Engine menu?
Infobox, which one is best to show Leela real evaluation.. I read that centipawns are not best..
And in Engine, should I select "Backend"... I am using CUDA... Node limit Infinite... Threads ?? is it CPU related, I have 8 cores or GPU because its CUDA version?
Btw. On my laptop with Nvidia 750M With leela 0.25 I am getting 5344 nod/sec 1200 more than with 0.25rc1.

Of course if any idea regarding Fritz Ill be really greatful.

fohristiwhirl  thanks a lot for your support and patience. You helped me a lot.

**Comment by MadMike1234** [comment]
![Nibbler working again](https://user-images.githubusercontent.com/64505251/80616045-b8baa080-8a40-11ea-9a1e-d9385375a85f.png)
![Nibbler podesavanja](https://user-images.githubusercontent.com/64505251/80616052-bb1cfa80-8a40-11ea-9868-0ab95363e1f7.png)

**Comment by MadMike1234** [comment]
Also whats best way to set position in Nibbler? :-D

**Comment by fohristiwhirl** [comment]
I think the default settings should be OK for Leela. Really it's not expected to work very well with Stockfish.

For positions, if you have the FEN you can click on the blue FEN, delete it all, paste in a new FEN, and press return.

**Comment by MadMike1234** [comment]
![Fritz working](https://user-images.githubusercontent.com/64505251/80616512-48f8e580-8a41-11ea-9e54-aa713550e537.png)
Thanks again amigo!
Now it working under Fritz as well... you have very good nose to detect the problem.. Amazing!

Hmm FEN is notation system isnt it? And you are talking about some program ?

**Comment by MadMike1234** [comment]
I got it.. but from somewhere I must enter it.. OK... I am usinf Fritz to make position than I copy FEN into Nibbler

**Comment by fohristiwhirl** [comment]
FEN is a line of text that specifies a Chess position, see <https://en.wikipedia.org/wiki/Forsyth-Edwards_Notation>.

**Comment by MadMike1234** [comment]
yes only I am not familiar to write FEN lines.. I have to use some other program isnt it?

**Comment by fohristiwhirl** [comment]
Yeah I'm afraid Nibbler has no "edit position" feature as of now.

**Comment by fohristiwhirl** [comment]
Oh by the way, you should likely edit config.json once again to make Nibbler stop outputting a log - it's surprising how quickly such a log can fill your hard drive.

**Comment by MadMike1234** [comment]
I did already. I really appreciate your support... i solved all opened items today :-D
