### ISSUE TITLE
Feature request: graphic showing the change of probabilities of win in a game

### ISSUE THREAD

**Issue by jorditg** [fohristiwhirl/nibbler#92]
Hi all,

Congratulations for your great graphical analysis app!

I would like to propose you a feature that I think it would be very interesting and useful for completing the analysis reported by the app. That is a graphic showing the change on the probabilities of win in every move of the game. Something similar to the graphical reported by lichess after its analysis. In this way it would be possible to obtain similar analysis using leela as an engine.

Thanks for your great work.

Regards,

Jordi

**Comment by fohristiwhirl** [comment]
Added to the list at #10
