### ISSUE TITLE
State logic is too complicated

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#94]
The logic of the various states Nibbler can be in is getting tangled. We should likely have a list of states:

* Totally halted
* Versus mode (as White) but it's Black's move
* Versus mode (as White) - running
* Versus mode (as Black) but it's White's move
* Versus mode (as Black) - running
* Self-play
* Auto-analysis

Or something...

Honestly the whole system of interaction with the engine is too complex.

**Comment by fohristiwhirl** [comment]
Eh maybe it's fine.

**Comment by lealgo** [comment]
How about this?

![Screenshot_20200513-152619](https://user-images.githubusercontent.com/12534727/81856116-511b4f80-952e-11ea-8e7b-7a9a3c41386d.jpg)

**Comment by fohristiwhirl** [comment]
Maybe. What I meant with this issue was that, behind the scenes, my internal logic was too complicated. Whether it's baffling to the user is another matter. :)

**Comment by lealgo** [comment]
Right.
Just another UI idea, Arena covers all possible states with four buttons:

![image](https://user-images.githubusercontent.com/12534727/81883623-b5a4d180-9563-11ea-8e09-93d39030ef85.png)

The gear button is "Move Now" and it forces the engine to make a move, if it's the engine's turn then it forces it to move, but if it's the user's turn then it moves on behalf of the user and swaps sides. The gear also serves as a Stop button.

The default state for Arena is "user vs engine". After the user moves the engine will reply. On Nibbler the default would be Edit or Analyze.

**Comment by fohristiwhirl** [comment]
@lealgo - I've made some changes; behind the scenes things are easier for me to reason about now, and I implemented a single item "play this colour" command.

Also, I implemented "analyse and lock" which lets you move pieces without disrupting the analysis. It would be great if you could try that a little and see if you can break it....

**Comment by lealgo** [comment]
@fohristiwhirl 

In general they work fine and I've not found any issue.

I think with Go and lock (analyse other pos.) the naming was confusing (to me?) at first, as it doesn't analyse with the engine. It's more like "try out some moves on myself".

The versus modes seem fine to me. Alternating self-play and auto-response worked OK I couldn't break it. The help text in "About versus mode" is outdated though.

**Comment by fohristiwhirl** [comment]
Thanks.

**Comment by fohristiwhirl** [comment]
> I think with Go and lock (analyse other pos.) the naming was confusing (to me?) at first, as it doesn't analyse with the engine.

Wait - was it clear that it was analysing the initial position while you moved around, though?

**Comment by lealgo** [comment]
> Wait - was it clear that it was analysing the initial position while you moved around, though?

I haven't realized that. Maybe I didn't notice because I had a node limit set and when I returned to the locked position the analyze was quieter as the limit was met.
