### ISSUE TITLE
Anyway of running with --no-sandbox, since I need to be root on my system?

### ISSUE THREAD

**Issue by ilpadrinohack** [fohristiwhirl/nibbler#98]
No config file where to disable non-root run

**Comment by fohristiwhirl** [comment]
Uh - I'm not sure I fully understand the question.

**Comment by ilpadrinohack** [comment]
Hi, basically when I try to run nibbler, no matter if it is the linux
release version or compiled from the source code (using electron), in both
of them says that is not possible to run it being root without --no-sandbox
flag. It occurs the same with Chrome web browser, but in this case I can
put the flag in the chrome bin file

**Comment by fohristiwhirl** [comment]
Sounds like a Chromium security feature.

Can you try running `./nibbler --no-sandbox` (whether this will work or not I don't know).

**Comment by ilpadrinohack** [comment]
I have tried this with no luck. Thanks anyway

**Comment by fohristiwhirl** [comment]
The other thing you could try is `electron --no-sandbox .` while in the src directory.

**Comment by ilpadrinohack** [comment]
Ok, I will try later at home

**Comment by ilpadrinohack** [comment]
Thanks very much. It works like a charm
